packages:
  - client
  - server
  - mobile

allowBuilds:
  '@nestjs/core': false
  '@scarf/scarf': false
  bcrypt: false
  mongodb-client-encryption: false
  puppeteer: false
  sharp: false
  unrs-resolver: false
